aim_node:
  ros__parameters:
    servo_port_name: '/dev/ttyUSB0'
    servo_baudrate: 115200
    servo_id: [1, 2]
    mid: [0, 2047, 2047]
    angle_range: [[0, 0], [-1400, 1400], [-650, 1024]]
    pid_gains:
      Kp: 0.08
      Ki: 0.0
      Kd: 0.01